create table if not exists submissions (
  id bigint generated by default as identity primary key,
  name text,
  email text,
  message text,
  files json,
  submitted_at timestamp with time zone default now()
);

-- Enable RLS for storage.objects
alter table storage.objects enable row level security;

-- Allow anyone to upload files to this bucket
create policy "public upload" on storage.objects
  for insert to public
  with check (bucket_id = 'webform-uploads');
